version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: always
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: always
    ports:
      - 5050:3000
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
