version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: always
    ports:
      - 5001:80
    volumes:
      - type: bind
        source: ./backend/app
        target: /usr/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
      - FLASK_APP_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend/
        target: /usr/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=postrootpass
      - POSTGRES_DB=flask000db
      - POSTGRES_USER=flask000user
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
