version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: always
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: ./backend
        target: /usr/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend/
        target: /usr/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - FLASK_DEBUG=1
